namespace JobFairPortal.DTOs
{
    /// <summary>DTO for creating a new co-admin. Password is auto-generated by the server.</summary>
    public class AdminCreateDto
    {
        public string Name { get; set; } = null!;
        public string Email { get; set; } = null!;
        /// <summary>The OTP the super admin received on their own email to authorize this action.</summary>
        public string Otp { get; set; } = null!;
    }

    /// <summary>DTO for sending an OTP to the calling super admin to authorize co-admin creation.</summary>
    public class AdminCreateOtpRequestDto
    {
        // No body needed — the super admin is identified via JWT claims.
        // This class is kept for extensibility / Swagger documentation.
    }

    /// <summary>DTO for verifying the super admin's OTP (pre-flight check from frontend).</summary>
    public class AdminVerifyOtpDto
    {
        public string Otp { get; set; } = null!;
    }
}
