// <auto-generated />
using System;
using JobFairPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobFairPortal.Migrations
{
    [DbContext(typeof(JobFairRecruitmentDbContext))]
    [Migration("20260119101229_AddedAttendeneceSystem")]
    partial class AddedAttendeneceSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobFair", b =>
                {
                    b.Property<int>("JobFairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobFairId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobFairId");

                    b.ToTable("JobFairs");
                });

            modelBuilder.Entity("JobFairPortal.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AchievementId"));

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AchievementId");

                    b.HasIndex("StudentId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("JobFairPortal.Models.AdminAttendanceSession", b =>
                {
                    b.Property<int>("AdminAttendanceSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminAttendanceSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByAdmin")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AdminAttendanceSessionId");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("JobFairId", "IsActive");

                    b.ToTable("AdminAttendanceSessions");
                });

            modelBuilder.Entity("JobFairPortal.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("JobFairPortal.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CertificationId"));

                    b.Property<string>("CredentialId")
                        .HasColumnType("text");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CertificationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("JobFairPortal.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("ArrivalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("text");

                    b.Property<string>("CompanyPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentJobFairId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<int>("InterviewDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KeyExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("KeyUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepsCount")
                        .HasColumnType("integer");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.HasIndex("CurrentJobFairId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("JobFairPortal.Models.CompanyContactLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkId");

                    b.HasIndex("CompanyId", "Platform")
                        .IsUnique();

                    b.ToTable("CompanyContactLinks");
                });

            modelBuilder.Entity("JobFairPortal.Models.CompanyJobFairParticipation", b =>
                {
                    b.Property<int>("ParticipationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipationId"));

                    b.Property<int>("ArrivalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("AttendanceToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("AttendanceTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("InterviewDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParticipationId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("RoomId");

                    b.HasIndex("CompanyId", "JobFairId")
                        .IsUnique();

                    b.ToTable("CompanyJobFairParticipations");
                });

            modelBuilder.Entity("JobFairPortal.Models.CompanyRequest", b =>
                {
                    b.Property<int>("CompanyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyRequestId"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompanyRequestId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobFairId", "Status");

                    b.ToTable("CompanyRequests");
                });

            modelBuilder.Entity("JobFairPortal.Models.ContactLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkId");

                    b.HasIndex("StudentId", "Platform")
                        .IsUnique();

                    b.ToTable("ContactLinks");
                });

            modelBuilder.Entity("JobFairPortal.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationId"));

                    b.Property<double?>("CGPA")
                        .HasColumnType("double precision");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("EducationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("JobFairPortal.Models.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("ExperienceId");

                    b.HasIndex("StudentId", "StartDate");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("JobFairPortal.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InterviewId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InterviewId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.HasIndex("RequestId");

                    b.HasIndex("StudentId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("JobFairPortal.Models.InterviewRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonForReject")
                        .HasColumnType("text");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.HasIndex("StudentId");

                    b.ToTable("InterviewRequests");
                });

            modelBuilder.Entity("JobFairPortal.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfJobs")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobFairPortal.Models.Notice", b =>
                {
                    b.Property<int>("NoticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoticeId"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoticeId");

                    b.HasIndex("JobFairId");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("JobFairPortal.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Supervisor")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("JobFairPortal.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoomId");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("JobFairPortal.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<decimal>("CGPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentJobFairId")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("CurrentJobFairId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("JobFairPortal.Models.StudentJobFairParticipation", b =>
                {
                    b.Property<int>("ParticipationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipationId"));

                    b.Property<bool>("HasRegistered")
                        .HasColumnType("boolean");

                    b.Property<int>("InterviewsAttended")
                        .HasColumnType("integer");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int>("OffersReceived")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParticipationId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("StudentId", "JobFairId")
                        .IsUnique();

                    b.ToTable("StudentJobFairParticipations");
                });

            modelBuilder.Entity("JobFairPortal.Models.StudentProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCreator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StudentId", "ProjectId")
                        .IsUnique();

                    b.ToTable("StudentProjects");
                });

            modelBuilder.Entity("JobFairPortal.Models.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SurveyId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("JobFairId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobFairId1")
                        .HasColumnType("integer");

                    b.Property<string>("Responses")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("SurveyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobFairId");

                    b.HasIndex("JobFairId1");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("JobFairPortal.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobFairPortal.Models.Achievement", b =>
                {
                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("Achievements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.AdminAttendanceSession", b =>
                {
                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobFair");
                });

            modelBuilder.Entity("JobFairPortal.Models.AuditLog", b =>
                {
                    b.HasOne("JobFairPortal.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("JobFairPortal.Models.Certification", b =>
                {
                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("Certifications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.Company", b =>
                {
                    b.HasOne("JobFair", "CurrentJobFair")
                        .WithMany()
                        .HasForeignKey("CurrentJobFairId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("Companies")
                        .HasForeignKey("JobFairId1");

                    b.HasOne("JobFairPortal.Models.User", "User")
                        .WithOne("Company")
                        .HasForeignKey("JobFairPortal.Models.Company", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentJobFair");

                    b.Navigation("JobFair");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFairPortal.Models.CompanyContactLink", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("CompanyContactLinks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobFairPortal.Models.CompanyJobFairParticipation", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("JobFairParticipations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFairPortal.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Company");

                    b.Navigation("JobFair");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("JobFairPortal.Models.CompanyRequest", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("CompanyRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("JobFair");
                });

            modelBuilder.Entity("JobFairPortal.Models.ContactLink", b =>
                {
                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("ContactLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.Education", b =>
                {
                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("Educations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.Experience", b =>
                {
                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("Experiences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.Interview", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("Interviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("Interviews")
                        .HasForeignKey("JobFairId1");

                    b.HasOne("JobFairPortal.Models.InterviewRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("Interviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("JobFair");

                    b.Navigation("Request");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.InterviewRequest", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("InterviewRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("InterviewRequests")
                        .HasForeignKey("JobFairId1");

                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("InterviewRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("JobFair");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.Job", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("Jobs")
                        .HasForeignKey("JobFairId1");

                    b.Navigation("Company");

                    b.Navigation("JobFair");
                });

            modelBuilder.Entity("JobFairPortal.Models.Notice", b =>
                {
                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobFair");
                });

            modelBuilder.Entity("JobFairPortal.Models.Room", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithOne("Room")
                        .HasForeignKey("JobFairPortal.Models.Room", "CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("Rooms")
                        .HasForeignKey("JobFairId1");

                    b.Navigation("Company");

                    b.Navigation("JobFair");
                });

            modelBuilder.Entity("JobFairPortal.Models.Student", b =>
                {
                    b.HasOne("JobFair", "CurrentJobFair")
                        .WithMany()
                        .HasForeignKey("CurrentJobFairId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("Students")
                        .HasForeignKey("JobFairId1");

                    b.HasOne("JobFairPortal.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("JobFairPortal.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentJobFair");

                    b.Navigation("JobFair");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFairPortal.Models.StudentJobFairParticipation", b =>
                {
                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("JobFairParticipations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobFair");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.StudentProject", b =>
                {
                    b.HasOne("JobFairPortal.Models.Project", "Project")
                        .WithMany("StudentProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFairPortal.Models.Student", "Student")
                        .WithMany("StudentProjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobFairPortal.Models.Survey", b =>
                {
                    b.HasOne("JobFairPortal.Models.Company", "Company")
                        .WithMany("Surveys")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", "JobFair")
                        .WithMany()
                        .HasForeignKey("JobFairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFair", null)
                        .WithMany("Surveys")
                        .HasForeignKey("JobFairId1");

                    b.Navigation("Company");

                    b.Navigation("JobFair");
                });

            modelBuilder.Entity("JobFair", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("InterviewRequests");

                    b.Navigation("Interviews");

                    b.Navigation("Jobs");

                    b.Navigation("Rooms");

                    b.Navigation("Students");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("JobFairPortal.Models.Company", b =>
                {
                    b.Navigation("CompanyContactLinks");

                    b.Navigation("CompanyRequests");

                    b.Navigation("InterviewRequests");

                    b.Navigation("Interviews");

                    b.Navigation("JobFairParticipations");

                    b.Navigation("Jobs");

                    b.Navigation("Room");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("JobFairPortal.Models.Project", b =>
                {
                    b.Navigation("StudentProjects");
                });

            modelBuilder.Entity("JobFairPortal.Models.Student", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Certifications");

                    b.Navigation("ContactLinks");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("InterviewRequests");

                    b.Navigation("Interviews");

                    b.Navigation("JobFairParticipations");

                    b.Navigation("StudentProjects");
                });

            modelBuilder.Entity("JobFairPortal.Models.User", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
