// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdKCuYdaY3FuIajayBz-16uJVFDjiDEUM',
    appId: '1:82967259176:web:adf61b7db83b21cdc6ed1d',
    messagingSenderId: '82967259176',
    projectId: 'hirebridge-c28e9',
    authDomain: 'hirebridge-c28e9.firebaseapp.com',
    storageBucket: 'hirebridge-c28e9.firebasestorage.app',
    measurementId: 'G-JDM3F9TTQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNulLDYH9WMc2LkHv4BvYvcm36Zf3AY44',
    appId: '1:82967259176:android:4069e3bfa67e9200c6ed1d',
    messagingSenderId: '82967259176',
    projectId: 'hirebridge-c28e9',
    storageBucket: 'hirebridge-c28e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAujncg0GvhQ-mON5X0FACxQjyHIcb3I8I',
    appId: '1:82967259176:ios:ab5037562ad7e9cfc6ed1d',
    messagingSenderId: '82967259176',
    projectId: 'hirebridge-c28e9',
    storageBucket: 'hirebridge-c28e9.firebasestorage.app',
    iosBundleId: 'com.example.studentJobFairPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdKCuYdaY3FuIajayBz-16uJVFDjiDEUM',
    appId: '1:82967259176:web:ccf0f98f332af0cbc6ed1d',
    messagingSenderId: '82967259176',
    projectId: 'hirebridge-c28e9',
    authDomain: 'hirebridge-c28e9.firebaseapp.com',
    storageBucket: 'hirebridge-c28e9.firebasestorage.app',
    measurementId: 'G-D4F7LBMZ9E',
  );
}
